<a href="https://colab.research.google.com/github/piotrowskaoliwia/Zadania-Domowe/blob/main/Oliwia_Piotrowska_Lab%20%7B5%7D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
def transpose(A):
   m, n = A.shape
   B = np.empty([n,m])

   for i in range(0,n):
      for j in range(0,m):
         B[i][j]=A[j][i]
   return B

m = np.random.randint(1,10)
n = np.random.randint(1,10)

X = np.random.randint(0,10,(m,n))

Y = transpose(X)
print (X)
print (Y)

[[4 2 6]
 [8 6 5]
 [0 9 5]
 [0 3 6]
 [8 2 5]]
[[4. 8. 0. 0. 8.]
 [2. 6. 9. 3. 2.]
 [6. 5. 5. 6. 5.]]
